version: '3.0'

services:

  php-fpm:
    image: ${COMPOSE_PROJECT_NAME}/php-fpm
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST_INTERNAL}
    entrypoint:
      - /bin/bash
      - -c
      - /usr/local/bin/dev-entrypoint.sh ${CURRENT_UID} ${CURRENT_GID}
    volumes:
      - ${PWD}/app:/app
      - ${PWD}/docker/build/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini


  nginx:
    image: ${COMPOSE_PROJECT_NAME}/nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    volumes:
      - ${PWD}/app:/app
    ports:
      - 8081:80

#  pgsql:
#    image: postgres:11-alpine
#    ports:
#      - 54321:5432
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=database
